# HTTP Request/Response Cycle - Lab

## Introduction 

In this lab, we'll make use of the `requests` module commands and properties seen in the previous lesson, to extract information for a web service called **"Open Notify"** to access NASA's space data. 

## Objectives

You will be able to:

* Explain the HTTP request/response cycle
* List the status codes of responses and their meanings
* Obtain and interpret status codes from responses
* Make HTTP GET and POST requests in python using the `requests` library

## Open Notify 

[Open Notify](http://open-notify.org/)  is an an open source project to provide a simple programming interface for some of NASA’s awesome data. This takes live raw data from NASA's systems and turn them into APIs related to space and spacecraft. We can access the following information from open notify. 

* Current Location of the International Space Station

* Number of People in Space

* Overhead Pass Predictions for the International Space Station
    
### API endpoints

Open Notify has several API endpoints. 
>An endpoint is a server route that is used to retrieve different data from the API. 

For example, the `/comments` endpoint on the Reddit API might retrieve information about comments, whereas the `/users` endpoint might retrieve data about users. To access them, you would add the endpoint to the base url of the API.

For the OpenNotify API, we have the following endpoints: 

1. Current Location of the International Space Station `/iss-now.json`
2. Number of People in Space `/astros.json`
3. Overhead Pass Predictions for the International Space Station `/iss-pass.json`    

The `.json` extension simply tells us that the data is being returned in a JSON format.

In this lab, we'll be querying this API to retrieve live data about the International Space Station (ISS). Details on OpenNofity, endpoints, syntax, and the services it offers can be viewed [Here](http://open-notify.org/Open-Notify-API/)

![](images/iss.jpg)

### Current location of International Space Station

The first endpoint we'll look at on Open Notify is the ` iss-now.json` endpoint (current location of international space station). This endpoint gets the current latitude and longitude of the International Space Station.  Perform the following tasks 
* Make a get request to get the latest position of the international space station from the opennotify api's `iss-now` endpoint at http://api.open-notify.org/iss-now.json
* Check the status code of the response
* Interpret the returned code

In [8]:
# Your Code Here
import requests
url='http://api.open-notify.org/iss-now.json'
response = requests.get(url)
r=response.json()

# Print the status code of the response
print(response.status_code)

200

In [ ]:
# Your comments

* Print the contents of the response and identify its current location

In [31]:
print(r)

{'message': 'success', 'iss_position': {'latitude': '10.5224', 'longitude': '95.0962'}, 'timestamp': 1739351743}

In [ ]:
# Interpret your results using the API

### Number of people in space

Let's repeat the above for the second endpoint, `astros.json`. It tells you how many people are currently in space. The format of the responses can be studied [HERE](http://open-notify.org/Open-Notify-API/People-In-Space/).

Read the above documentation and perform the following tasks:

* Get the response from astros.json endpoint
* Count how many people are currently in space
* List the names of people currently in space.

In [24]:
# Your Code Here
import requests
url2='http://api.open-notify.org/astros.json'
response2 = requests.get(url2)
print(response2.status_code)

#have the data json format

r2=response2.json()
# print(r2)
print(r2.keys())
type(r2['people'])

#count how many people are currently in space
# print(f'Number of people in space', len(r2['people']))

200
dict_keys(['people', 'number', 'message'])

list

In [30]:
# convert r2 to a dataframe

import pandas as pd
df = pd.DataFrame(r2)
df

# Interpret the Results - How many people are in space and what are their names

                                              people  number  message
0         {'craft': 'ISS', 'name': 'Oleg Kononenko'}      12  success
1           {'craft': 'ISS', 'name': 'Nikolai Chub'}      12  success
2   {'craft': 'ISS', 'name': 'Tracy Caldwell Dyson'}      12  success
3       {'craft': 'ISS', 'name': 'Matthew Dominick'}      12  success
4        {'craft': 'ISS', 'name': 'Michael Barratt'}      12  success
5          {'craft': 'ISS', 'name': 'Jeanette Epps'}      12  success
6    {'craft': 'ISS', 'name': 'Alexander Grebenkin'}      12  success
7          {'craft': 'ISS', 'name': 'Butch Wilmore'}      12  success
8        {'craft': 'ISS', 'name': 'Sunita Williams'}      12  success
9        {'craft': 'Tiangong', 'name': 'Li Guangsu'}      12  success
10          {'craft': 'Tiangong', 'name': 'Li Cong'}      12  success
11       {'craft': 'Tiangong', 'name': 'Ye Guangfu'}      12  success

In [23]:
#count the number of people in space

# print(f'Number of people in space: {len(r2["people"])}')
print(f'Number of people: {len(r2["people"])}')

Number of people: 12

In [26]:
#list their names
Names =[ ]
for person in r2['people']:
    Names.append(person['name'])

print(f'Names of people in space: {Names}')
print (len(Names))

Names of people in space: ['Oleg Kononenko', 'Nikolai Chub', 'Tracy Caldwell Dyson', 'Matthew Dominick', 'Michael Barratt', 'Jeanette Epps', 'Alexander Grebenkin', 'Butch Wilmore', 'Sunita Williams', 'Li Guangsu', 'Li Cong', 'Ye Guangfu']
12

In [ ]:
# Interpret the Results - How many people are in space and what are their names

In [28]:
type(r2['people'][0])

dict

In [29]:
#convert the list of people into a dataframe

import pandas as pd
df = pd.DataFrame(r2['people'])
df

       craft                  name
0        ISS        Oleg Kononenko
1        ISS          Nikolai Chub
2        ISS  Tracy Caldwell Dyson
3        ISS      Matthew Dominick
4        ISS       Michael Barratt
5        ISS         Jeanette Epps
6        ISS   Alexander Grebenkin
7        ISS         Butch Wilmore
8        ISS       Sunita Williams
9   Tiangong            Li Guangsu
10  Tiangong               Li Cong
11  Tiangong            Ye Guangfu

## Summary 

In this lesson, we saw how we can use request and response methods to query an Open API. We also saw how to look at the contents returned with the API calls and how to parse them. Next, we'll look at connecting to APIs which are not OPEN, i.e. we would need to pass in some authentication information and filter the results.